apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-webui
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.webService.externalIps }}
  externalIPs:
    {{- range .Values.webService.externalIps }}
    - {{ . }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
