{{- if .Values.vpn.privoxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-privoxy
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.btService.type }}
  ports:
    - port: 8118
      targetPort: privoxy
      protocol: TCP
      name: privoxy
  {{- if .Values.vpn.privoxy.externalIps }}
  externalIPs:
    {{- range .Values.vpn.privoxy.externalIps }}
    - {{ . }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
{{- end }}
