apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-bt
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.btService.type }}
  ports:
    - port: {{ .Values.btService.port }}
      targetPort: bittorrent-tcp
      protocol: TCP
      name: bittorrent-tcp
    - port: {{ .Values.btService.port }}
      targetPort: bittorrent-udp
      protocol: UDP
      name: bittorrent-udp
  {{- if .Values.btService.externalIps }}
  externalIPs:
    {{- range .Values.btService.externalIps }}
    - {{ . }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
