{{- if and (eq .Values.metrics.enabled true) ( eq .Values.metrics.serviceMonitor.enabled true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
        {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
        {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
        {{- end }}
        {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
        {{- end }}
      path: /metrics
{{- end }}
