{{- if and .Values.vpn.enabled .Values.vpn.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qbittorrent.fullname" . }}-wg
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
data:
  wg0.conf: |
    {{- .Values.vpn.config | nindent 4 }}
{{- end}}
