---
apiVersion: v2
name: mealie
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgresql
    version: 18.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
