#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
strategy:
  type: Recreate

controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/mealie-recipes/mealie
          tag: v3.3.1
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables.
        # @default -- See below
        env:
          TZ: UTC

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http: 
        port: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      main: # the controller with the "main" identifier
        main: # the container with the "main" identifier
          - path: /app/data/
            readOnly: false

# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
postgresql:
  enabled: false
#  auth:
#    postgresPassword: ""
#    username: ""
#    password: ""
#    database: ""
  persistence:
    enabled: true
    storageClass:
    accessModes:
      - ReadWriteOnce
