controllers:
  main:
    enabled: true
    containers:
      main:
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
