{{- if not .Values.mealie.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.databaseSecretName" . }}
  labels: {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.mealie.postgresql.user | quote }}
  password: {{ .Values.mealie.postgresql.password | quote }}
  host: {{ .Values.mealie.postgresql.host | quote }}
  port: {{ .Values.mealie.postgresql.port | quote }}
  dbname: {{ .Values.mealie.postgresql.database | quote }}
{{- end }}
