apiVersion: v1
appVersion: "0"
description: Helm chart for generic app on Kubernetes
home: https://github.com/RubxKube/common-charts
keywords:
- generic
- monolithic
- ingress
kubeVersion: '>= 1.18'
maintainers:
- email: github@une-pause-cafe.fr
  name: QJOLY
  url: https://une-tasse-de.cafe
name: common
sources:
- https://github.com/RubxKube/common-charts
version: v0.4.5
